package com.example.statemachine.travel;

public enum TravelState {
  PLANNING, PAPERWORK, WAITING_DOCUMENTS, DOCUMENTS_READY,
  CHOOSE_TRANSPORT, BOOK_PLANE, BOOK_TRAIN, BOOK_CAR,
  BOOK_ACCOMMODATION, PACK_LUGGAGE, TRAVELING, COMPLETION
}
